source 'http://rubygems.org'

gem 'cucumber', '2.0.0'
gem 'rspec'
gem 'rake'
gem 'watir'
gem 'watir-webdriver'
gem 'watir-classic'
gem 'selenium-webdriver'
gem 'rspec-expectations'
gem 'data_magic'
gem 'log4r'