source 'http://rubygems.org'

gem 'watir', '6.10.3'
gem 'rspec', '3.6.0'
gem 'gherkin'
gem 'cucumber', '3.1.0'
gem 'rake'
gem 'data_magic'
gem 'log4r'
gem 'rautomation'
gem 'yml_reader'
gem 'holidays'
gem 'spreadsheet'
gem 'measured'
#gem 'mysql2'

#gem 'watir', '6.2.1'
#gem 'selenium-webdriver', '3.4.0'
#gem 'cucumber', '2.4.0'
#gem 'selenium-webdriver'